name: apps_bouncer
description: |
  Application that keeps track of running processes,
  snitching bad-behaving ones to the user, who can choose to kill them.
version: 1.0.0
repository: https://github.com/renatoathaydes/apps_bouncer

environment:
  sdk: ^3.3.2

dev_dependencies:
  dartle: ^0.26.0
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  logging: ^1.2.0
  schemake: ^0.5.0
  yaml: ^3.1.2

executables:
  apps_bouncer:
