name: Build

on: [ push ]

jobs:
  build-mac:
    runs-on: macos-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart dartle.dart --disable-cache
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Dartle Tests
          path: build/*.json
          reporter: dart-json
